### ISSUE TITLE
Error in running phyloacc_post.py

### ISSUE THREAD

**Issue by ningyawen** [phyloacc/PhyloAcc-test-data#2]
Dear authors:

After the batches have completed, I use `phyloacc_post.py -i phyloacc-test` to gather the outputs. But I get an error: 
```
--------------------------------------------------------
**Error OP5: Error reading tree from interface log file!
--------------------------------------------------------
```
How should I do to solve this error. 

Thanks!
Yawen

**Comment by YellowStar96** [comment]
Hello, Yawen
Have you solved the problem? I also encountered a similar error. How did you solve it?
Thank you.

Best regards,
Xin Huang

**Comment by ningyawen** [comment]
Hello, Xin

You can solve this bug by upgrading phyloacc to version 2.1.0, which includes `phyloacc_post.py`.

Yawen
